name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
          
      - uses: actions/checkout@v3
      - name: Checkout and install requirements
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          cache: 'pip'
      - run: pip install -r requirements.txt

      - name: Check free space
        run: |
          echo "Free space:"
          df -h
          
      - uses: actions/checkout@v3
      - name: Build and minify the Docker image
        run: ./deploy.sh
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Docker Push
        run: docker push $DOCKER_USER/pumi:latest; docker push $DOCKER_USER/pumi-slim:latest
        
        
      

    
